project:
  type: site
  render:
    - 01_cloud_concepts.ipynb
    - 02_aws_global_infra.ipynb
    - 03_interact_with_aws.ipynb
    - 04_ec2.ipynb
    - 05_s3.ipynb
    - 06_rds.ipynb
    - 07_outro.ipynb
    - 08_challenge.ipynb
  title: "Introduction to AWS"
  output-dir: ./_site

website:
  title: "Introduction to AWS"
  favicon: ./images/favicon.ico
  site-url: https://prp0x80.github.io/intro-to-aws
  repo-url: https://github.com/prp0x80/intro-to-aws
  repo-actions: [edit, issue]
  page-footer:
    left: |
      Powered by [Quarto](https://quarto.org/)
    right:
      - icon: twitter
        href: https://twitter.com/KainosAcademy
        aria-label: Kainos Academy Twitter
      - icon: github
        href: https://github.com/prp0x80/intro-to-aws
        aria-label: Intro to AWS

  sidebar:
    style: "floating"
    search: true
    contents:
      - 01_cloud_concepts.ipynb
      - 02_aws_global_infra.ipynb
      - 03_interact_with_aws.ipynb
      - section: "AWS Core Services"
        contents:
        - 04_ec2.ipynb
        - 05_s3.ipynb
        - 06_rds.ipynb
      - 07_outro.ipynb
      - 08_challenge.ipynb

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
